#testmake: property_treeTest.cpp
#	g++ -o property_treeTest property_treeTest.cpp 
#

CC=g++
FGLAGS=-I.
testmake: property_treeTest.cpp 
	$(CC) -o property_treeTest  property_treeTest.cpp

#DD=g++
#FGLAGS=-I.
#testmake: property_treeTest.cpp 
#	$(DD) -o property_treeTest -o property_treeTest.o property_treeTest.cpp

